name: progress

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}

      - name: Get yarn cache directory path
        id: cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: npx ts-node ./src/cmd.ts > README.md

      - name:  Commit and Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '38056766+ysmtegsr@users.noreply.github.com'
          git commit -am '[bot] update README automatically'
          git push
